### PR TITLE
Fix: Update navigation height less variable to css variable. 

### PR DESCRIPTION
**Pull request by StuartNicholls**
Update to less variable with adapt css variable.

Fixes: #49

### CODE REVIEW

**Review by guywillis — APPROVED** [review]
👀

**Comment by swashbuck** [comment]
@StuartNicholls Should probably mention the required framework version? https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.34.0

**Comment by StuartNicholls** [comment]
> @StuartNicholls Should probably mention the required core/framework version? https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.34.0
> 
> _bower.json_, _package.json_, and maybe add it to the readme.

Thats a very good point, didn't consider that as was operating in CG Kineo. 

Re. bower.json, I think we just need to add the framework number to package.json though. @guywillis is that correct?

@swashbuck is that the correct version? Also, we should probably fix that here: https://github.com/adaptlearning/adapt-contrib-trickle/blob/bef0310950855ed0fde4f17835942e19cb73d5e8/package.json#L4 - and anywhere this might have been updated?

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-backgroundSwitcher/blob/7252c9ebbdd0bb9efd2003ac0361f6ca44c55f7c/package.json#L32

Part of the release process copies the package.json over the top if the bower JSON. You only need to update the fw version in the package.json as long as you follow the release cycle the bower.json will be updated automatically.

**Comment by swashbuck** [comment]
> @swashbuck is that the correct version? Also, we should probably fix that here: https://github.com/adaptlearning/adapt-contrib-trickle/blob/bef0310950855ed0fde4f17835942e19cb73d5e8/package.json#L4 - and anywhere this might have been updated?

@StuartNicholls Yes, agreed that other plugins will need the framework version updated.

What I'm not sure about is how we specify the requirement. The Framework tags aren't the same as the Core plugin tags. We only specify the required _Framework_ version in package.json.

**Review by swashbuck — APPROVED** [review]
👍

**Comment by kirsty-hames** [comment]
> What I'm not sure about is how we specify the requirement. The Framework tags aren't the same as the Core plugin tags. We only specify the required _Framework_ version in package.json:

Did anyone confirm this as I'm not sure about this myself so would be good to know? I currently download the core release and check the FW version in the _package.json_.

In which case, shouldn't this have a minimum FW requirement of v5.20.2? I'm not sure where v5.30.3 came from.

**Comment by guywillis** [comment]
> > What I'm not sure about is how we specify the requirement. The Framework tags aren't the same as the Core plugin tags. We only specify the required _Framework_ version in package.json:
> 
> Did anyone confirm this as I'm not sure about this myself so would be good to know? I currently download the core release and check the FW version in the _package.json_.
> 
> In which case, shouldn't this have a minimum FW requirement of v5.20.2? I'm not sure where v5.30.3 came from.

I doubt this is the optimal way of finding out but this was my process:

* This PR adds the `var(--adapt-navigation-height)` css variable
* I searched where this variable first appears in core which is 6.34.0
* The corresponding framework release that is the same date as the core release was 5.30.3

**Comment by StuartNicholls** [comment]
> > > What I'm not sure about is how we specify the requirement. The Framework tags aren't the same as the Core plugin tags. We only specify the required _Framework_ version in package.json:
> > 
> > 
> > Did anyone confirm this as I'm not sure about this myself so would be good to know? I currently download the core release and check the FW version in the _package.json_.
> > In which case, shouldn't this have a minimum FW requirement of v5.20.2? I'm not sure where v5.30.3 came from.
> 
> I doubt this is the optimal way of finding out but this was my process:
> 
> * This PR adds the `var(--adapt-navigation-height)` css variable
> * I searched where this variable first appears in core which is 6.34.0
> * The corresponding framework release that is the same date as the core release was 5.30.3

This is exactly what I do

**Review by kirsty-hames — APPROVED** [review]

**Pull request merged**
